title: Haobing Guo's Homepage
page-top-title: Haobing Guo
top-section-bg-text: Computer Science
home-subtitle: Haobing Guo&ensp;|&ensp;郭昊冰
copyright-text: '&copy; Haobing Guo 2025-2026. All Rights Reserved.'
